spring.application.name=notifications

# Configuração padrão do RabbitMQ (Docker Local)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.connection-timeout=10000
# Banco de Dados (H2 ou SQLite)
spring.datasource.url=jdbc:h2:file:./data/[nome-do-servico]db
# ou para SQLite:
# spring.datasource.url=jdbc:sqlite:./data/[nome-do-servico].db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# Exchange e Routing Keys (ajustar conforme o projeto)
rabbitmq.exchange.name=app.exchange
rabbitmq.routing.event1=event.routing1
rabbitmq.routing.event2=event.routing2