# Porta do servico
server.port=8084

# Nome da aplicacao
spring.application.name=notifications

# RabbitMQ (Docker Local)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.connection-timeout=10000

# Banco de Dados SQLite (arquivo local persistido em ./data/notifications.db)
spring.datasource.url=jdbc:sqlite:./data/notifications.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Topologia de Mensageria - Exchanges
rabbitmq.exchange.events=events.topic
rabbitmq.exchange.payments=payments.fanout

# Topologia de Mensageria - Filas
rabbitmq.queue.events=notifications.events.queue
rabbitmq.queue.payment=notif.payment-confirmed.queue
rabbitmq.queue.checkin=notif.checkin.queue
rabbitmq.queue.soldout=notif.soldout.queue

# Routing Keys
rabbitmq.routing.event-created=event.created
rabbitmq.routing.ticket-checked=ticket.checked
rabbitmq.routing.event-soldout=event.soldout