server.port=8083
spring.application.name=payments

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}
spring.rabbitmq.connection-timeout=10000

# Persistencia com SQLite
spring.datasource.url=jdbc:sqlite:./data/payments.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Topologia AMQP
rabbitmq.exchange.tickets-direct=tickets.direct
rabbitmq.routing.ticket-purchased=ticket.purchased
rabbitmq.queue.payment-process=payment.process.queue

rabbitmq.exchange.payments-fanout=payments.fanout
rabbitmq.queue.tickets-paid=tickets.payment-confirmed.queue
rabbitmq.queue.events-paid=events.payment-confirmed.queue
rabbitmq.queue.notif-paid=notif.payment-confirmed.queue