spring.application.name=tickets
server.port=8082

# RabbitMQ (Docker Local)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.connection-timeout=10000

# SQLite
spring.datasource.url=jdbc:sqlite:./data/tickets.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Exchanges e routing keys
rabbitmq.exchange.events=events.topic
rabbitmq.exchange.tickets=tickets.direct
rabbitmq.exchange.payments=payments.fanout
rabbitmq.routing.event-created=event.created
rabbitmq.routing.ticket-purchased=ticket.purchased
rabbitmq.routing.ticket-checked=ticket.checked
rabbitmq.routing.event-soldout=event.soldout
rabbitmq.queue.event-created=tickets.event-create.queue
rabbitmq.queue.payment-confirmed=tickets.payment-confirmed.queue